name: flutterapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdftron_flutter:
    git:
      url: git://github.com/PDFTron/pdftron-flutter.git
  flutter_svg: 0.17.4
  flutter_rating_bar: 3.0.1
  flutter_staggered_grid_view: 0.3.1
  permission_handler: ^5.0.1+1
#  permission_handler: 4.4.0
  path_provider: ^1.4.0
  webview_flutter: 0.3.22+1
  intl:
  cached_network_image: 2.2.0
  auto_size_text: 2.1.0
  http:
  video_player:
  open_iconic_flutter: 0.3.0
  wakelock: 0.1.4+2
  audioplayers: 0.15.1
  nb_utils: 3.2.0
  flutter_downloader:
  lottie: 0.5.1
  flutter_html: 0.8.2
  splash_screen_view: 1.0.1
  image_picker: 0.6.4
  dots_indicator: ^1.2.0
  cupertino_icons: ^0.1.3
  provider:
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  flutter_vector_icons: 0.2.1
  url_launcher: ^5.4.2
  sqflite: ^1.2.0
  firebase_analytics: 5.0.11
  firebase_crashlytics: 0.1.3+3
  flutter_windowmanager: 0.0.2
  epub_viewer: ^0.1.8
  flutter_pdfview: 1.0.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
#  onesignal_flutter: ^2.6.1
#  admob_flutter: 1.0.0
  mobx_codegen: ^1.1.2
  build_runner: ^1.9.0
  open_file: ^3.0.3
  epub: ^2.1.0
  ext_storage: ^1.0.3
  receive_sharing_intent: ^1.4.2
  shared_preferences: ^0.5.12+4
#dependency_overrides:
#  cached_network_image: 2.5.0
#  flutter_svg: 0.19.2+1

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - book_loader.json
  - app_loader.json
  - more_data_loader2.json
  - more_data_loader1.json
  - big.jpg
  - get_now_btn.png
  - main_logo.png
  - gift.png
  - trans_logo.png
  - bg.png
  - play_btn.png
  - socialfacebook.png
  - socialgoogle.png
  - error.png
  - noInternet.png
  - epub.png
  - back.png
  - walkimages1.png
  - walkimages2.png
  - walkimages3.png
  - walkimages4.png
  - downloads.png
  - music.png
  - pdf.png
  - video.png
  - default.png
  - logo.png
  - share.png
  - love.png
  - librarysolid.png
  - sunglasses.png
  - vector7.png
  - vector10.png
  - vector12.png
  - vector13.png
  - vector15.png
  - 1.png
  - intersect.png
  - search.png
  - vector8.png
  - backgound.png
  - BookDetails.png
  - bookmark.png
  - bookmark_dark.png
  - chevron.png
  - edit.png
  - eye.png
  - gear.png
  - help.png
  - home-run.png
  - link.png
  - logout.png
  - menu.png
  - next.png
  - pause.png
  - supermarket.png
  - trash.png
  - password.png
  - user.png
  - privacy.png
  - world.png
  - info.png
  - walk_through_bg.png
  - ic_profile.png
  - ic_mode.png
  - verified.png
  - padlock.png
  - ic_CallRing.png
  - ic_Fb.png
  - ic_Inst.png
  - ic_Whatsapp.png
  - ic_Twitter.png
  - login.png
  - lang/en.json
  - lang/fr.json
  - lang/es.json
  - lang/af.json
  - lang/de.json
  - lang/in.json
  - lang/vi.json
  - lang/tr.json
  - lang/hi.json
  - lang/ar.json
  - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
    - family: Jost
      fonts:
        - asset: fonts/Jost-Bold.ttf
        - asset: fonts/Jost-Italic.ttf
        - asset: fonts/Jost-Medium.ttf
        - asset: fonts/Jost-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
